name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Install Go
        uses: actions/setup-go@v2

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt-get install libx11-dev libxfixes-dev --yes
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage

      - name: Build
        run: |
          export APPIMAGE_EXTRACT_AND_RUN=1
          PATH=".:$PATH"; make appimage
          rm linuxdeploy-x86_64.AppImage

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.AppImage
